import SwiftUI
import AppCoreShared

/// Reconstructed high-fidelity Exposure Warning Overlay (UI-204).
/// Displays real-time clipping mask generated by COExposureWarningRenderer.
public struct ExposureWarningOverlay: View {
    let image: NSImage
    @ObservedObject var manager = COClippingOverlayManager.shared
    
    public var body: some View {
        Group {
            if let mask = manager.clippingMask {
                Image(nsImage: mask)
                    .resizable()
                    .interpolation(.none)
            }
        }
        .allowsHitTesting(false)
    }
}
