import Foundation

/// Reconstructed SQLite Schema for Capture One.
/// Based on disassembly of DataCore.

public struct DatabaseSchema {
    
    public static let createTablesQuery = """
    CREATE TABLE ZIMAGE (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZAUTHOR VARCHAR, ZIMAGEUUID VARCHAR,
        ZINDEX INTEGER, ZRAWMETADATAMODIFICATIONDATE FLOAT, ZSETTINGSMODIFICATIONDATE FLOAT,
        ZVERSION INTEGER, ZXMPMETADATAMODIFICATIONDATE FLOAT, ZIMPORTDATE FLOAT,
        ZSIDECARPATH VARCHAR, ZBITMAPHASH VARCHAR, ZDISPLAYNAME VARCHAR,
        ZISINSIDECATALOG BOOLEAN, ZIMAGELOCATION INTEGER, ZIMAGEFILENAME VARCHAR,
        ZISTRASHED BOOLEAN, ZWIDTH INTEGER, ZHEIGHT INTEGER, ZISO INTEGER
    );
    
    CREATE TABLE ZVARIANT (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZINDEX INTEGER,
        ZVARIANTUUID VARCHAR, ZIMAGE INTEGER, ZISMODIFIED BOOLEAN,
        ZPROCESSINGENGINE INTEGER, ZRATING INTEGER, ZCOLOR_TAG INTEGER,
        ZLENS_DISTORTION FLOAT, ZLENS_SHARPNESS_FALLOFF FLOAT, ZLENS_LIGHT_FALLOFF FLOAT,
        ZLENS_SHIFT_X FLOAT, ZLENS_SHIFT_Y FLOAT, ZCHROMATIC_ABERRATION BOOLEAN,
        ZDIFFRACTION BOOLEAN, ZLCC_ACTIVE BOOLEAN, ZLCC_PROFILE_UUID VARCHAR
    );
    
    CREATE TABLE ZVARIANTLAYER (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZINDEX INTEGER,
        ZVARIANT INTEGER, ZENABLED BOOLEAN, ZNAME VARCHAR,
        ZEXPOSURE FLOAT, ZCONTRAST FLOAT, ZSATURATION FLOAT, ZBRIGHTNESS FLOAT,
        ZCROP VARCHAR, ZROTATION FLOAT, ZWHITEBALANCE VARCHAR, ZICCPROFILE VARCHAR,
        ZLENS_DISTORTION FLOAT, ZLENS_SHARPNESS_FALLOFF FLOAT, ZLENS_LIGHT_FALLOFF FLOAT
    );
    
    CREATE TABLE ZCOLLECTION (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZUUID VARCHAR UNIQUE,
        ZNAME VARCHAR, ZPARENT INTEGER, ZSORTORDER VARCHAR,
        ZFOLDERLOCATION INTEGER, ZPREDICATE BLOB
    );
    
    CREATE TABLE ZVERSIONINFO (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZVERSION INTEGER,
        ZCOMPATIBLEVERSION INTEGER, ZAUTHOR VARCHAR, ZCOMPATIBILITY INTEGER,
        ZFORMAT INTEGER
    );
    
    CREATE TABLE ZDOCUMENTCONTENT (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZDOCUMENTUUID VARCHAR,
        ZDOCUMENTTYPE INTEGER, ZDATECREATED FLOAT, ZSELECTEDCOLLECTION INTEGER,
        ZHOTFOLDERDESTINATIONLOCATION INTEGER,
        ZCAPTUREFOLDER VARCHAR, ZSELECTSFOLDER VARCHAR, ZOUTPUTFOLDER VARCHAR, ZTRASHFOLDER VARCHAR
    );
    
    CREATE TABLE ZDOCUMENTSETTING (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZSETTINGKEY VARCHAR UNIQUE,
        ZSETTINGVALUE VARCHAR
    );
    
    CREATE TABLE ZSIDECAR (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZIMAGE INTEGER,
        ZPATH VARCHAR, ZTYPE INTEGER, ZLASTSYNCDATE FLOAT
    );
    
    CREATE TABLE ZMETADATA (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZIMAGE INTEGER, ZVARIANT INTEGER,
        ZCREATOR VARCHAR, ZCOPYRIGHT VARCHAR, ZDESCRIPTION VARCHAR, ZKEYWORDS VARCHAR,
        ZISO INTEGER, ZAPERTURE FLOAT, ZSHUTTER FLOAT, ZFOCALLENGTH INTEGER,
        ZMAKE VARCHAR, ZMODEL VARCHAR
    );
    """
    
    // MARK: - Column Names (Constants for type safety)
    public enum Image: String {
        case uuid = "ZIMAGEUUID"
        case path = "ZSIDECARPATH"
        case isTrashed = "ZISTRASHED"
    }
    
    public enum Variant: String {
        case uuid = "ZVARIANTUUID"
        case isModified = "ZISMODIFIED"
        case image = "ZIMAGE"
    }
}
