import Foundation

/// Reconstructed SQLite Schema for Capture One.
/// Based on disassembly of DataCore.

public struct DatabaseSchema {
    
    public static let createTablesQuery = """
    CREATE TABLE ZIMAGE (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZAUTHOR VARCHAR, ZIMAGEUUID VARCHAR,
        ZINDEX INTEGER, ZRAWMETADATAMODIFICATIONDATE FLOAT, ZSETTINGSMODIFICATIONDATE FLOAT,
        ZVERSION INTEGER, ZXMPMETADATAMODIFICATIONDATE FLOAT, ZIMPORTDATE FLOAT,
        ZSIDECARPATH VARCHAR, ZBITMAPHASH VARCHAR, ZDISPLAYNAME VARCHAR,
        ZISINSIDECATALOG BOOLEAN, ZIMAGELOCATION INTEGER, ZIMAGEFILENAME VARCHAR,
        ZISTRASHED BOOLEAN, ZWIDTH INTEGER, ZHEIGHT INTEGER, ZISO INTEGER
    );
    
    CREATE TABLE ZVARIANT (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZINDEX INTEGER,
        ZVARIANTUUID VARCHAR, ZIMAGE INTEGER, ZISMODIFIED BOOLEAN,
        ZPROCESSINGENGINE INTEGER
    );
    
    CREATE TABLE ZVARIANTLAYER (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZINDEX INTEGER,
        ZVARIANT INTEGER, ZENABLED BOOLEAN, ZNAME VARCHAR,
        ZEXPOSURE FLOAT, ZCONTRAST FLOAT, ZSATURATION FLOAT, ZBRIGHTNESS FLOAT,
        ZCROP VARCHAR, ZROTATION FLOAT, ZWHITEBALANCE VARCHAR, ZICCPROFILE VARCHAR
    );
    
    CREATE TABLE ZCOLLECTION (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZUUID VARCHAR UNIQUE,
        ZNAME VARCHAR, ZPARENT INTEGER, ZSORTORDER VARCHAR,
        ZFOLDERLOCATION INTEGER
    );
    
    CREATE TABLE ZVERSIONINFO (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZVERSION INTEGER,
        ZCOMPATIBLEVERSION INTEGER, ZAUTHOR VARCHAR, ZCOMPATIBILITY INTEGER,
        ZFORMAT INTEGER
    );
    
    CREATE TABLE ZDOCUMENTCONTENT (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZDOCUMENTUUID VARCHAR,
        ZDOCUMENTTYPE INTEGER, ZDATECREATED FLOAT, ZSELECTEDCOLLECTION INTEGER,
        ZHOTFOLDERDESTINATIONLOCATION INTEGER
    );
    
    CREATE TABLE ZDOCUMENTSETTING (
        Z_ENT INTEGER, Z_PK INTEGER PRIMARY KEY, ZSETTINGKEY VARCHAR UNIQUE,
        ZSETTINGVALUE VARCHAR
    );
    """
    
    // MARK: - Column Names (Constants for type safety)
    public enum Image: String {
        case uuid = "ZIMAGEUUID"
        case path = "ZSIDECARPATH"
        case isTrashed = "ZISTRASHED"
    }
    
    public enum Variant: String {
        case uuid = "ZVARIANTUUID"
        case isModified = "ZISMODIFIED"
        case image = "ZIMAGE"
    }
}
